@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.farmingforblockheads.compat;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;